services:
  mysql:
    image: mysql:8.4.3-oracle
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet-api
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api-container
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DATABASE: wallet-api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql

volumes:
  db-data: