
/*
DROP TABLE IF EXISTS GLOBAL_PARAMETER;
DROP TABLE IF EXISTS ASSET_HISTORYS;
DROP TABLE IF EXISTS TOKEN_HISTORY;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS WALLET;
DROP TABLE IF EXISTS ASSET;
*/

CREATE TABLE IF NOT EXISTS GLOBAL_PARAMETER
(
    gp_key     VARCHAR(30) PRIMARY KEY,
    gp_value   VARCHAR(100) NOT NULL,
    gp_comment VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS WALLET
(
    ID             BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMAIL          VARCHAR(50) UNIQUE                  NOT NULL,
    PUBLIC_ADDRESS VARCHAR(200) UNIQUE                 NOT NULL,
    PRIVATE_KEY    VARCHAR(200) UNIQUE                 NOT NULL,
    TOTAL          DECIMAL(40, 20)                     NOT NULL,
    DT_CREATED     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_UPDATED     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TOKEN
(
    ID                 INT PRIMARY KEY AUTO_INCREMENT,
    ID_NAME            VARCHAR(50)                         NOT NULL,
    NR_RANK            INT                                 NOT NULL,
    SYMBOL             VARCHAR(10)                         NOT NULL,
    NAME               VARCHAR(50)                         NOT NULL,
    SUPPLY             DECIMAL(40, 20),
    MAX_SUPPLY         DECIMAL(40, 20),
    MARKET_CAP_USD     DECIMAL(40, 20),
    VOLUME_USD_24H     DECIMAL(40, 20),
    PRICE_USD          DECIMAL(40, 20),
    CHANGE_PERCENT_24H DECIMAL(40, 20),
    VWAP_24H           DECIMAL(40, 20),
    DT_CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_UPDATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TOKEN_HISTORY
(
    ID                   BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_TOKEN             INT                                 NOT NULL,
    PRICE                DECIMAL(40, 20),
    DT_CREATED           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_COINCAP_TIMESTAMP TIMESTAMP                           NOT NULL,
    FOREIGN KEY (ID_TOKEN) REFERENCES TOKEN (ID)
);

CREATE TABLE IF NOT EXISTS ASSET
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY   DECIMAL(40, 20)                     NOT NULL,
    PRICE      DECIMAL(40, 20)                     NOT NULL,
    `VALUE`    DECIMAL(40, 20)                     NOT NULL,
    ID_WALLET  BIGINT                              NOT NULL,
    ID_TOKEN   INT                                 NOT NULL,
    DT_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_WALLET) REFERENCES WALLET (ID),
    FOREIGN KEY (ID_TOKEN) REFERENCES TOKEN (ID)
);

CREATE TABLE IF NOT EXISTS ASSET_HISTORY
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_ASSET   INT                                 NOT NULL,
    QUANTITY   DECIMAL(40, 20),
    PRICE      DECIMAL(40, 20),
    DT_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_ASSET) REFERENCES ASSET (ID)
);
