spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:mysql://localhost:3306/wallet-api?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8081
