spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:wallet-api}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true #&useTimezone=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8081

global:
  configuration:
    asset-update-time-scheduler: 20 #Time in minutes
