spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:mysql://localhost:3306/wallet-api?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8081


global:
  configuration:
    asset-update-time-scheduler: 20 #Time in minutes
