CREATE TABLE WALLET
(
    `ID`             BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
    `PUBLIC_ADDRESS` VARCHAR(50)     NOT NULL,
    `PRIVATE_KEY`    VARCHAR(50)     NOT NULL,
    `TOTAL`          DECIMAL(20, 20) NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE ASSET
(
    `ID`        BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
    `ASSET_ID`  BINARY(16) DEFAULT (UUID_TO_BIN(UUID())),
    `SYMBOL`    VARCHAR(5)      NOT NULL,
    `QUANTITY`  DECIMAL(20, 20) NOT NULL,
    `PRICE`     DECIMAL(20, 20) NOT NULL,
    `VALUE`     DECIMAL(20, 20) NOT NULL,
    `WALLET_ID` BIGINT(10)      NOT NULL,
    FOREIGN KEY (`WALLET_ID`) REFERENCES WALLET (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE GLOBAL_ASSET
(
    `ID`                 INT PRIMARY KEY AUTO_INCREMENT,
    `ID_NAME`            VARCHAR(10)     NOT NULL,
    `RANK`               INT             NOT NULL,
    `SYMBOL`             VARCHAR(10)     NOT NULL,
    `NAME`               VARCHAR(10)     NOT NULL,
    `SUPPLY`             DECIMAL(20, 20) NOT NULL,
    `MAX_SUPPLY`         DECIMAL(20, 20) NOT NULL,
    `MARKET_CAP_USD`     DECIMAL(20, 20) NOT NULL,
    `VOLUME_USED_24H`    DECIMAL(20, 20) NOT NULL,
    `PRICE_USD`          DECIMAL(20, 20) NOT NULL,
    `CHANGE_PERCENT_24H` DECIMAL(20, 20) NOT NULL,
    `VWAP_24H`           DECIMAL(20, 20) NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;