CREATE TABLE TOKEN_HISTORY
(
    `ID`                   INT PRIMARY KEY AUTO_INCREMENT,
    `ID_TOKEN`             INT                                NOT NULL,
    `PRICE`                DECIMAL(40, 20)                    NULL,
    `DT_CREATED`           DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `DT_COINCAP_TIMESTAMP` TIMESTAMP                          NOT NULL,
    FOREIGN KEY (`ID_TOKEN`) REFERENCES TOKEN (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE INDEX IDX_TOKEN_HISTORY_ID ON TOKEN_HISTORY (ID);