CREATE TABLE ASSET_HISTORY
(
    `ID`         INT PRIMARY KEY AUTO_INCREMENT,
    `ID_ASSET`   BIGINT(10)                         NOT NULL,
    `QUANTITY`   DECIMAL(40, 20)                    NULL,
    `PRICE`      DECIMAL(40, 20)                    NULL,
    `DT_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (`ID_ASSET`) REFERENCES ASSET (`ID`)
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4;

CREATE INDEX IDX_ASSET_HISTORY_ID ON ASSET_HISTORY (ID);
CREATE INDEX IDX_ASSET_HISTORY_DT_CREATED ON ASSET_HISTORY (DT_CREATED);